Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/',signup,name="signup"),
    path('send_email/',send_email,name="send_email"),
    path('verify_email/',verify_email,name="verify_email"),
    path('pw_finder/',pw_finder,name="pw_finder"),
    path('delete_account/', delete_account,name="delete_account"),
    path('terms_of_use/',terms_of_use,name="terms_of_use"),
    path('privacy/',privacy,name="privacy"),
    path('nickname_redundant_check/',nickname_redundant_check,name="nickname_redundant_check"),
]

main/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name ="main"
urlpatterns = [
    path('', start, name="start"),
    path('mainpage_competition', mainpage_competition, name="mainpage_competition"),
    path('mainpage_entrepreneur/', mainpage_entrepreneur, name="mainpage_entrepreneur"),
    path('mainpage_supporters/', mainpage_supporters, name="mainpage_supporters"),
    path('search/<str:f>', search, name="search"),
    path('second.html', second, name="second"),
    path('guide/', guide, name="guide"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'
urlpatterns = [
    path('write/', write, name="write"),
    path('new/', new, name="new"),
    path('crew_search/<int:id>', detail, name="detail"),
    path('temporary_save_post', temporary_save_post, name="temporary_save_post"),
    path('wrote_post', wrote_post, name="wrote_post"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/', mypage, name="mypage"),
    path('detail_profile/', detail_profile, name="detail_profile"),
    path('update_profile_pic/',update_profile_pic, name="update_profile_pic"),
    path('edit_portfolio/',edit_portfolio, name="edit_portfolio"),
    path('edit_profile/',edit_profile, name="edit_profile"),
    path('apply_manager/<str:page>',apply_manager, name="apply_manager"),
    path('detail_apply/<str:page>/<int:id>',detail_apply, name="detail_apply"),
    path('respond_apply',respond_apply, name="respond_apply"),
]

Project/templates/base.html
<!doctype html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>CO_끼리</title>
</head>

<body>
    {% include 'shared/_navbar.html' %}
    {% block content %}

    {% endblock %}
</body>

</html>

Project/templates/base_mainpage.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
    <link
        href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@700&family=Noto+Sans+KR:wght@100;400&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base_mainpage.css' %}?after">
    
    {% block style %}{% endblock %}
    <title>mainpage</title>
</head>

<body style="margin:0px;">
    <section class="container">
        <section class="header">
            <section class="logo">
                <section class="logobar">
                    <div class="logo_left">
                        <div id="logo_image"></div>
                        <div id="logo_letter"></div>
                    </div>
                    <div class="logo_right">
                        {% if user.is_authenticated %}
                        {% else %}
                        <div class="login">
                            <a href="{% url 'accounts:login' %}">
                                <p>로그인</p>
                            </a>
                        </div>
                        {% endif %}
                    </div>
                </section>
            </section>

            <section class="banner">
                <a href="{% url 'main:guide' %}">
                <div id="banner_image"></div>
                </a>            
            </section>

            <section class="iconbar">
                <section class="iconbar_box">
                    <div class="icon_1">
                        {% if user.is_authenticated %}
                        <a href="{% url 'post:wrote_post' %}">
                            {% else %}
                            <a href="{% url 'accounts:login' %}" onclick="return confirm('로그인 후 이용해주세요');">
                                {% endif %}
                                <i class="fas fa-pen-alt" style="color: #70c488;"></i>
                            </a>
                            <p>글쓰기</p>
                    </div>
                    <div class="icon_2">
                        <i class="fas fa-home"></i>
                        <p>홈</p>
                    </div>

                    <div class="icon_3">
                        {% if user.is_authenticated %}
                        <a href="{% url 'users:mypage' %}">
                            {% else %}
                            <a href="{% url 'accounts:login' %}" onclick="return confirm('로그인 후 이용해주세요');">
                                {% endif %}
                                <i class="fas fa-user-alt" style="color: #66c081;"></i>
                                <p>마이</p>
                            </a>
                    </div>
                </section>
            </section>

            <section class="searchbar">
                <form action="{% url 'main:search' ' ' %}" method="POST">
                    {% csrf_token %}
                    <div class="search_row1">
                        <input type="text" name="word" id="" placeholder="Search">
                        <button type="submit" name="submit" id="submit_btn">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>

                    <div class="search_row2">
                        <div>
                            <select name="field" id="search_field">
                                <option value="전체">모집 분야</option>
                                <option value="공모전">공모전</option>
                                <option value="프로젝트">프로젝트</option>
                                <option value="대외활동">대외활동</option>
                                <option value="창업">창업</option>
                            </select>
                        </div>
                        <div>
                            <select name="track" id="search_track">
                                <option value="전체">모집 트랙</option>
                                <option value="기획">기획</option>
                                <option value="마케터">마케터</option>
                                <option value="영상">영상</option>
                                <option value="디자인">디자인</option>
                                <option value="개발">개발</option>
                                <option value="기자단">기자단</option>
                                <option value="봉사">봉사</option>
                                <option value="기타">기타</option>
                            </select>
                        </div>
                    </div>

                </form>
            </section>

            <section class="categorybar">
                <section class="category_box">
                    <div id="track1">
                        <a href="{% url 'main:mainpage_competition' %}">
                            <p>공모전,프로젝트</p>
                        </a>
                    </div>
                    <div id="track2">
                        <a href="{% url 'main:mainpage_supporters' %}">
                            <p>대외활동</p>
                        </a>
                    </div>
                    <div id="track3">
                        <a href="{% url 'main:mainpage_entrepreneur' %}">
                            <p>창업</p>
                        </a>
                    </div>
                </section>
            </section>
            {% block teamlist %}

            {% endblock%}
            <section class="emptybar">
                <p>ver 1.1</p>
                <p>likeliondgu 똑쟁이들</p>
                <p>develop by. 김혜수, 박지호, 이주원, 전병현, 차은호</p>
            </section>
        </section>
    </section>



</body>

</html>