Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/',signup,name="signup"),
    path('send_email/',send_email,name="send_email"),
    path('verify_email/',verify_email,name="verify_email"),
    path('pw_finder/',pw_finder,name="pw_finder"),
    path('delete_account/', delete_account,name="delete_account"),
    path('terms_of_use/',terms_of_use,name="terms_of_use"),
    path('privacy/',privacy,name="privacy"),
    path('nickname_redundant_check/',nickname_redundant_check,name="nickname_redundant_check"),
]

main/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name ="main"
urlpatterns = [
    path('', start, name="start"),
    path('mainpage_competition', mainpage_competition, name="mainpage_competition"),
    path('mainpage_entrepreneur/', mainpage_entrepreneur, name="mainpage_entrepreneur"),
    path('mainpage_supporters/', mainpage_supporters, name="mainpage_supporters"),
    path('search/<str:f>', search, name="search"),
    path('second.html', second, name="second"),
    path('guide/', guide, name="guide"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from users.models import User

def profile_pic_path(instance, filename):
	# MEDEIA_ROOT/user_<pk>/ 경로로 <filename> 이름으로 업로드
    return f'profile_pics/{filename}_user_{instance.pk}'

class Profile(models.Model):
    gender_choices = (
        ('남성', '남성'),
        ('여성', '여성'),
        ('기타', '기타'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #기존에 제공하는 User 모델을 Profile 모델과 1ㄷ1 연결한다.
    name = models.TextField(max_length=10)
    nickname = models.TextField(max_length=10)
    age = models.PositiveIntegerField(null=True,blank=True)
    gender = models.CharField(max_length=8,choices=gender_choices,null=True,default='기타')
    major = models.TextField(max_length=15,blank=True)
    contact = models.TextField(max_length=15,blank=True)
    about_me = models.TextField(max_length=200,blank=True)
    profile_pic = models.ImageField(upload_to=profile_pic_path,default='default/profile_pic_default.png')
    def __str__(self):  # admin에서 표시될 user 필드 정보 설정
        return self.nickname

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from .models import User,Profile
import json,secrets
from django.http import JsonResponse, HttpResponse
from django.core.cache import cache
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage


# Create your views here.

def login(request):
    if request.method == 'POST':
        
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(request, email=email,password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('main:mainpage_competition')
        
        else:
            return render(request,'accounts/login.html',{'Wrong':True})
        
    elif request.method == 'GET':
        return render(request, 'accounts/login.html')

def terms_of_use(request):
    return render(request,'accounts/terms_of_use.html')

def privacy(request):
    return render(request,'accounts/privacy.html')


def logout(request):
    auth.logout(request)
    return redirect("main:mainpage_competition")

def signup(request):
    if request.method == 'POST':
        email = request.POST['email']

        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(
                email= email,
                password=request.POST['password'],
            )
            nickname = request.POST['nickname']
            name = request.POST['name']
            profile = Profile(user = user,nickname=nickname,name=name)
            profile.save()

            auth.login(request,user)
            return redirect('/')


    return render(request,'accounts/signup.html')

def delete_account(request):
    user = request.user
    user.delete()
    return render(request,'accounts/login.html')

def pw_finder(request):
    if request.method == 'POST':
        email = request.POST['email']
        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.get(email = email)
            user.set_password(request.POST['password'])
            user.save()
            return redirect('accounts:login')
    else:
        return render(request,'accounts/pw_finder.html')

def send_email(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        email = data.get('email')
        if data.get('pagename') == 'pw_finder':
            if not User.objects.filter(email = email).exists():
                response_data = {
                'message': '존재하지 않는 이메일입니다.',
                }
                return JsonResponse(response_data)
        if data.get('pagename') == 'signup':
            if User.objects.filter(email = email).exists():
                response_data = {
                'message': '이미 가입된 이메일입니다.',
                }
                return JsonResponse(response_data)
        dgu_domain_list = ['dongguk.edu','dgu.edu','dgu.ac.kr']
        domain = email.split('@')[1]
        if domain not in dgu_domain_list:
                response_data = {
                'message': '동국대학교 이메일을 사용해주세요.',
                }
                return JsonResponse(response_data)
        token = generate_auth_code(email)
        message = render_to_string('accounts/email_verify.html', {
            'token': token,
        })

        mail_title = "CO끼리 이메일 인증코드 발송"
        to_email = EmailMessage(mail_title, message, to=[email])
        to_email.send()

        response_data = {
            'email': email,
            'message': '인증번호 전송 완료',
        }
        return JsonResponse(response_data)
    # POST 요청 이외의 경우는 에러 처리
    response_data = {
        'error': 'Invalid request method'
    }
    return JsonResponse(response_data, status=400)



def generate_auth_code(email):
    # 임시 인증 코드 생성 로직
    auth_code = secrets.token_hex(4)
    # 캐시에 인증 코드 저장
    cache_key = f"auth_code_{email}"
    cache.set(cache_key, auth_code, timeout=600)  # 10분 동안 유효하도록 설정
    return auth_code

def verify_email(request):
    # 캐시에서 인증 코드 가져오기
    data = json.loads(request.body)
    email = data.get('email')
    code = data.get('code')

    cache_key = f"auth_code_{email}"
    cached_code = cache.get(cache_key)

    if cached_code and cached_code == code:
        cache.delete(cache_key)
        return JsonResponse({'is_same': True})
    else:
        return JsonResponse({'is_same': False})
    

def nickname_redundant_check(request):
    data = json.loads(request.body)
    nickname = data.get('nickname')
    #만일 nickname이 중복될 때
    is_redundant = Profile.objects.filter(nickname=nickname).exists()
    if is_redundant:
        return JsonResponse({'is_redundant' : is_redundant})
    else:
        return JsonResponse({'is_redundant' : is_redundant})
    

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">

    <title>로그인</title>
</head>

<body>
    <!-- 로그인 글씨 -->

    <div class="top">
        <div class="logo"></div>
        <p><span style="font-size: 40px;"><b>로그인</b><br></span>
            <span style="font-size: 20px;">login</span>
        </p>

    </div>

    <!-- 입력칸 ~ 로그인 버튼 -->

    <div id="input">
        <form action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            <label for="id">동국대학교 이메일</label>
            <input type="text" placeholder="이메일을 입력해주세요" name="email" required>

            <br><br>

            <label for="pw">비밀번호</label>
            <input type="password" placeholder="비밀번호를 입력해주세요" name="password" required>
            <br><br><br>

            <section>
                <button style="border: none;">로그인하기</button>
            </section>
        </form>
    </div>

    <!-- 비밀번호찾기 버튼 -->
    <section>
        <div id="find_pw" style="color:#66C081; text-decoration: underline; font-size: 16px;">
            <a href="{% url 'accounts:pw_finder' %}" style="color: #66C081;">비밀번호 찾기</a>
        </div>
    </section>
    <section style=" font-size: 20px;">아직 회원이 아니신가요?
    </section>

    <section>
        <div id="join">
            <a href="{%url 'accounts:signup' %}">회원가입</a>
        </div>
        </form>
    </section>
    {% if Wrong %}
    <script>


            function regist() {
                alert('확인 후 페이지가 넘어가지 않는다면 잘못된 계정입니다!');
            }


        alert('아이디/비밀번호를 확인해주세요');

    </script>
    {% endif %}

</body>

</html>

accounts/templates/accounts/pw_finder.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/pw_finder.css' %}">

    <title>비밀번호 찾기</title>

</head>

<body>

    <!-- 고정 시계바 -->

    <div class="lock">
        <p style="font-size: 28px;">비밀번호 찾기<br><br>
    </div>

    <div id="input">
        <form action="{% url 'accounts:pw_finder' %}" method="POST">
            {% csrf_token %}
            <label for="name">동국대학교 이메일</label>
            <div id="input_btn">
            <input type="email" placeholder="예) likelion@dgu.ac.kr" name="email" id="input_email" required>

                <div class="check">
                    <a onclick="sendEmail()">인증 전송</a></div>
            </div>

            <label for="name">이메일 인증</label>
            <input type="text" placeholder="인증번호를 입력해주세요" name="code" id="input_code" required>

            <div class="check">
                <a onclick="verify_code()";">인증 확인</a></div>


            <label for="name">새로운 비밀번호 입력</label>
            <input type="password" placeholder="영문/숫자/특수문자 조합 가능 (8자 이상)" name="password" required>

            <label for="name">새로운 비밀번호 확인</label>
            <input type="password" placeholder="비밀번호를 다시 한 번 입력해주세요" name="confirm" required>
    </div>

    </div>
    <section>
        <button style="border: none;">비밀번호 저장하기</button>
        </form>
    </section>
    </div>
    <script>
        function sendEmail() {
            var emailInput = document.getElementById("input_email");
            var email = emailInput.value;
            var pagename = 'pw_finder';

            fetch("{% url 'accounts:send_email' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({ email: email, pagename: pagename })
            })
                .then(response => response.json())
                .then(data => {
                    alert(data.message);
                    console.log(data);
                })
                .catch(error => {
                    // 에러 처리
                    alert("error");
                });
        }

        function verify_code() {
            var emailInput = document.getElementById("input_email");
            var codeInput = document.getElementById("input_code");
            var email = emailInput.value, code = codeInput.value;
            fetch("{% url 'accounts:verify_email' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({ email: email, code: code })
            })
                .then(response => response.json())
                .then(data => {
                    if (data.is_same === true) {
                        alert('인증이 완료되었습니다!')
                        console.log("일치");
                    } else if (data.is_same === false) {
                        alert('다시 시도해주세요.')
                        console.log("불일치");
                    } else {
                        console.log("예외 처리");
                    }
                })
                .catch(error => {
                    alert("error");
                });
        }</script>
</body>


</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
    <title>회원가입</title>

</head>

<body>
    <!-- 고정 시계바 -->

    <!-- 로그인 글씨 -->

    <div id="top">
        <img src="{% static 'images/logo.png' %}" alt="로고" width="56px" height="44.21px">
        <p><span style="font-size: 40px;"><b>회원가입</b><br></span>
            <span style="font-size: 20px;">Sign up</span>
        </p>
    </div>

    <!-- 입력칸 -->


    <div id="input">
        <form method="POST" action="{% url 'accounts:signup' %}">
            {% csrf_token %}
            <label for="name">이름</label>
            <input type="text" placeholder="이름을 입력해주세요" name="name" required>

            <!-- 인증번호 맞는지 확인 -->
            <div id="check3">
                <a onclick="verify_code()">확인</a>
            </div>

            <label for="name">동국대학교 이메일</label>
            <input type="email" placeholder="예) likelion@dgu.ac.kr" name="email" id="input_email" required>

            <!-- 이메일 보내는 버튼 -->
            <div id="test">
                <a onclick="sendEmail()">인증번호 전송</a>
            </div>
            <!-- 인증번호가 제대로 왔는지 확인하는 버튼 -->
            <label for="name">이메일 인증</label>
            <input type="text" placeholder="인증번호를 입력해주세요" name="code" id="input_code" required>

            <div id="check_2">
                <a onclick="nickname_redundant_check()">중복 확인</a>
            </div>

            <label for="name" style="padding-top: 0;">닉네임</label>
            <input type="text" placeholder="닉네임은 추후 수정 불가능합니다" name="nickname" id="input_nickname" equired>

            <label for="name">비밀번호</label>
            <input type="password" placeholder="영문/숫자/특수문자 조합 가능 (8자 이상)" name="password" id="password" required>
            <span id="password-error" style="color: #ff0000;"></span>

            <label for="name">비밀번호 확인</label>
            <input type="password" placeholder="비밀번호를 다시 한 번 입력해주세요" name="confirm" id="confirm_password" required>
            <span id="confirm-password-error" style="color: red;"></span>


            <!-- 동의항목 -->

            <section><br>
                <div class="agree">
                    <input type="checkbox" name="[]" value="check" width="12.8%" required> 서비스 이용약관 동의 (필수)
                    <span style="margin-left: 70px;"><a href="{% url 'accounts:terms_of_use' %}"
                            style="color: gray; text-decoration: underline;">상세보기</a></span>
                </div>

                <div class="agree">
                    <input type="checkbox" name="[]" value="check" width="12.8%" required> 개인정보 수집 및 이용 동의 (필수)
                    <span style="margin-left: 31px;"><a href="{% url 'accounts:privacy' %}"
                            style="color: gray; text-decoration: underline;">상세보기</a></span>
                </div>


                <div class="agree">
                    <input type="checkbox" name="[]" value="check" width="12.8%" required> 만 14세 이상입니다 (필수)
                </div>

                <div class="agree">
                    <input type="checkbox" name="[]" value="check" width="12.8%"> 광고성 정보 수신 동의 (선택)
                </div>
            </section>

            <section join>
                <div id="join">
                    <button style="border: none; background-color: gray;" id="signup" disabled="true">회원가입하기</button>
                </div>
            </section>
        </form>
    </div>
    </div>
    <script>

        function redirectToPage() {
            window.location.href = '#';
        }

        var is_vaild_email = false;
        function setIsValidEmail(value) {
            is_vaild_email = value;
        }
        var is_vaild_nickname = false;
        function setIsValidNickname(value) {
            is_vaild_nickname = value;
        }
        var is_vaild_password = false;
        var is_confirm_password = false;

        function enable_or_disable_signup() {
            var button = document.getElementById("signup");
            if (is_vaild_nickname && is_vaild_email && is_vaild_password && is_confirm_password) {
                button.style.backgroundColor = '#FF8859';
                button.disabled = false;
            }
            else {
                button.style.backgroundColor = 'gray';
                button.disabled = true;
            }
        }

        function sendEmail() {
            var emailInput = document.getElementById("input_email");
            var email = emailInput.value;
            var pagename = 'signup';

            fetch("{% url 'accounts:send_email' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({ email: email, pagename: pagename })
            })
                .then(response => response.json())
                .then(data => {
                    alert(data.message);
                    console.log(data);
                })
                .catch(error => {
                    // 에러 처리
                    alert("알 수 없는 문제가 발생했습니다.");
                });
        }

        // gpt //
        function verify_code() {
            is_vaild_email = false;
            var emailInput = document.getElementById("input_email");
            var codeInput = document.getElementById("input_code");
            var email = emailInput.value, code = codeInput.value;
            fetch("{% url 'accounts:verify_email' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({ email: email, code: code })
            })
                .then(response => response.json())
                .then(data => {
                    if (data.is_same === true) {


                        setIsValidEmail(true)
                        enable_or_disable_signup()
                        console.log("Verification code is correct");
                        alert('인증번호가 확인되었습니다.')
                    } else {
                        setIsValidEmail(false)
                        console.log("Verification code is incorrect");
                        alert('인증번호를 다시 확인해주세요.')
                    }
                })
                .catch(error => {
                    console.log("Error occurred during verification");
                    alert("다시 시도하세요");
                });
        }

        // 여기까지~~~~~

        function nickname_redundant_check() {
            var nicknameInput = document.getElementById("input_nickname");
            var nickname = nicknameInput.value;
            fetch("{% url 'accounts:nickname_redundant_check' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({ nickname: nickname })
            })
                .then(response => response.json())
                .then(data => {
                    if (data.is_redundant === true) {
                        //중복될 때
                        alert('사용 불가능한 닉네임입니다.')
                        setIsValidNickname(false)
                        console.log("중복");
                    } else if (data.is_redundant === false) {
                        //중복되지 않을때
                        alert('사용 가능한 닉네임입니다.')
                        setIsValidNickname(true)
                        enable_or_disable_signup()
                        console.log("중복X");
                    } else {
                        console.log("예외 처리");
                    }
                })
                .catch(error => {
                    alert("error");
                });
        }

        document.getElementById('password').addEventListener('input', validatePassword);
        document.getElementById('confirm_password').addEventListener('input', validateConfirmPassword);

        function validatePassword() {
            var passwordInput = document.getElementById('password');
            var password = passwordInput.value;
            var passwordError = document.getElementById('password-error');

            if (password.length < 8) {
                is_vaild_password = false;
                passwordError.textContent = '비밀번호는 8자 이상이어야 합니다.';
            }
            else if (!(password.includes('@') || password.includes('!') || password.includes('?') || password.includes('#') || password.includes('&') || password.includes('*'))) {
                is_vaild_password = false;
                passwordError.textContent = '비밀번호는 특수문자(@,!,?,#,&.*)를 포함해야합니다.';
            }
            else {
                is_vaild_password = true;
                enable_or_disable_signup()
                passwordError.textContent = '';
            }
        }

        function validateConfirmPassword() {
            var passwordInput = document.getElementById('password');
            var confirmPasswordInput = document.getElementById('confirm_password');
            var password = passwordInput.value;
            var confirmPassword = confirmPasswordInput.value;
            var confirmPasswordError = document.getElementById('confirm-password-error');

            if (password !== confirmPassword) {
                confirmPasswordError.textContent = '비밀번호가 일치하지 않습니다.';
            } else {
                is_confirm_password = true;
                enable_or_disable_signup()
                confirmPasswordError.textContent = '';
            }
        }
    </script>

</body>

</html>