Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/',signup,name="signup"),
    path('send_email/',send_email,name="send_email"),
    path('verify_email/',verify_email,name="verify_email"),
    path('pw_finder/',pw_finder,name="pw_finder"),
    path('delete_account/', delete_account,name="delete_account"),
    path('terms_of_use/',terms_of_use,name="terms_of_use"),
    path('privacy/',privacy,name="privacy"),
    path('nickname_redundant_check/',nickname_redundant_check,name="nickname_redundant_check"),
]

main/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name ="main"
urlpatterns = [
    path('', start, name="start"),
    path('mainpage_competition', mainpage_competition, name="mainpage_competition"),
    path('mainpage_entrepreneur/', mainpage_entrepreneur, name="mainpage_entrepreneur"),
    path('mainpage_supporters/', mainpage_supporters, name="mainpage_supporters"),
    path('search/<str:f>', search, name="search"),
    path('second.html', second, name="second"),
    path('guide/', guide, name="guide"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/', mypage, name="mypage"),
    path('detail_profile/', detail_profile, name="detail_profile"),
    path('update_profile_pic/',update_profile_pic, name="update_profile_pic"),
    path('edit_portfolio/',edit_portfolio, name="edit_portfolio"),
    path('edit_profile/',edit_profile, name="edit_profile"),
    path('apply_manager/<str:page>',apply_manager, name="apply_manager"),
    path('detail_apply/<str:page>/<int:id>',detail_apply, name="detail_apply"),
    path('respond_apply',respond_apply, name="respond_apply"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager

# Create your models here.

# username 필드를 제거했기에 기존 유저 모델을 만드는 매서드에 username없이도 작동할 수 있도록 설정
class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)
    
# django에서 사용하는 AbstractUser를 상속받는 User 클래스 선언
class User(AbstractUser):
    # 기본 AbstractUser를 상속받아 수정
    username = None  # email만 사용할 것 이기에 제거
    email = models.EmailField(unique=True)  # email 필드를 주요 식별자로 사용

    USERNAME_FIELD = 'email'  # 인증 시 사용할 필드를 email로 설정
    REQUIRED_FIELDS = []  # createsuperuser 커맨드 사용 시 필요한 정보
    
    objects = UserManager()
    # 추가적인 필드들을 정의

users/views.py
from django.shortcuts import render,redirect
from django.utils import timezone
from accounts.models import Profile
from post.models import Apply,Post
import os,json
# Create your views here.
def mypage(request):
    if request.method == 'POST':
        edit_profile = Profile.objects.get(user=request.user)
        if request.POST['age'] :
            edit_profile.age = request.POST['age']
        else:
            edit_profile.age = None
        edit_profile.gender = request.POST['gender']
        edit_profile.major = request.POST['major']
        edit_profile.contact = request.POST['contact']
        edit_profile.about_me = request.POST['about_me']
        edit_profile.save()
        return render(request, 'users/mypage.html', {'profile':edit_profile })

    elif request.method == 'GET':
        profile = Profile.objects.get(user=request.user)
        return render(request, 'users/mypage.html', {'profile' : profile})

def detail_profile(request):
    if request.user is None:
        return redirect('accounts:login')
    else:
        profile = Profile.objects.get(user=request.user)
        return render(request, 'users/detail_profile.html', {'profile' : profile})

def edit_portfolio(request):
    if request.user is None:
        return redirect('accounts:login')
    else:
        profile = Profile.objects.get(user=request.user)
        return render(request,'users/edit_portfolio.html',  {'profile' : profile})

def edit_profile(request):
    if request.user is None:
        return redirect('accounts:login')
    else:
        profile = Profile.objects.get(user=request.user)
        return render(request,'users/edit_profile.html',  {'profile' : profile})

def update_profile_pic(request):
    update_profile = Profile.objects.get(user=request.user)
    if request.POST['action'] == "기본 이미지로 변경":
        if update_profile.profile_pic != 'default/profile_pic_default.png':
            os.remove(update_profile.profile_pic.path)
        update_profile.profile_pic = 'default/profile_pic_default.png'
        update_profile.save()
        return redirect('users:detail_profile')
    
    elif request.POST['action'] == '수정완료': 
        if len(request.FILES) != 0:
            if len(update_profile.profile_pic) > 0 and update_profile.profile_pic != 'default/profile_pic_default.png':
                os.remove(update_profile.profile_pic.path)
            update_profile.profile_pic = request.FILES['image']
            update_profile.save()
        return redirect('users:detail_profile')

def apply_manager(request, page):
    user = request.user
    profile = Profile.objects.get(user=user)
    if page == 'my_apply':
        applies = Apply.objects.filter(writer=user).order_by('-pub_date')
        return render(request,'users/apply_manager.html',{'profile': profile, 'applies' : applies, 'page' : page})
    elif page == 'rcv_apply':
        posts_by_user = Post.objects.filter(writer=user).order_by('-pub_date')
        applies = Apply.objects.filter(target_Post__in=posts_by_user)
        return render(request,'users/apply_manager.html',{'profile': profile, 'applies' : applies, 'page':page})

def detail_apply(request,page,id):
    apply = Apply.objects.get(id=id)
    profile = Profile.objects.get(user=apply.writer)
    if page == 'my_apply':
        return render(request, 'users/detail_my_apply.html',{'profile':profile, 'apply':apply})
    elif page == 'rcv_apply':
        return render(request, 'users/detail_rcv_apply.html',{'profile':profile, 'apply':apply})

def respond_apply(request):
    data = json.loads(request.body)
    id = data.get('id')
    reply = data.get('reply')
    status = data.get('status')
    apply = Apply.objects.get(id=id)
    apply.reply = reply
    apply.status = status
    apply.save()
    profile = Profile.objects.get(user=apply.writer)
    return redirect('users/detail_rcv_apply.html',{'profile':profile, 'apply':apply})

users/templates/users/apply_manager.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="chrome">
    <link rel="stylesheet" type="text/css" href="{% static 'css/apply_manager.css' %}?after" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if page == 'rcv_apply' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_orange.css' %}" />
    <style>
        .writing_category {
            min-height: 600px;
            width: 100%;
            background-color: #FF9D77;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .check_btn {
        width: 220px;
        height: 40px;
        background-color: #FF9D77;
        color: white;
        font-size: 14px;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 5px;
        margin-left: auto;
        margin-top: auto;
        }
    </style>
    {% else %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_green.css' %}" />
    <style>
        .writing_category {
            background-color: #66C081;
            display: flex;
            flex-direction: column;
            align-items: center;
            min-height: 600px;
        }

        .check_btn {
        width: 220px;
        height: 40px;
        background-color: #66C081;
        color: white;
        font-size: 14px;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 5px;
        margin-left: auto;
        margin-top: auto;
        }
    </style>
    {% endif %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
    <title>지원 관리</title>
</head>

<body>
    <section class="container">
        <section class="header">
            {% include 'shared/_navbar.html' %}
            <section class="write">
                <h1>지원 관리</h1>
                <div class="write_right">
                    <a href="{% url 'users:detail_profile' %}">
                        <i class="fas fa-cog" style="color: #747474; font-size: 30px;"></i>
                        <p>내 정보 수정</p>
                    </a>
                </div>
            </section>

            <section class="categorybar">
                <div id="track1">
                    <a href="{% url 'users:apply_manager' 'rcv_apply' %}">
                        <p>받은 지원</p>
                    </a>
                </div>
                <div id="track2">
                    <a href="{% url 'users:apply_manager' 'my_apply' %}">
                        <p>나의 지원</p>
                    </a>
                </div>
            </section>

            <section class="writing_category">
                {% if applies %}
                {% for apply in applies %}
                    <div class="team">
                        <div class="team_pic">
                            <img src="{{ apply.target_Post.image.url }}" alt="사진">
                        </div>
                        <div class="right">
                            <h1>{{ apply.target_Post.team_name }}</h1>
                            <p>{{ apply.target_Post.title }}</p>
                            <div class="check_btn">
                                <a href="{% url 'users:detail_apply' page apply.id %}">
                                    <p>
                                        {{apply.writer.profile.nickname}}님 지원서 확인하기 </p>
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
                {% endfor %}
                {% else %}
                <p style="font-size: 20px; font-weight: 600; text-align: center;">현재 지원이 없습니다.</p>
                {% endif %}
            </section>
</body>

users/templates/users/detail_profile.html
<!DOCTYPE html>
<html lang=" ko">
{% load static %}

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/detail_profile.css' %}" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet" />
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Co/mpatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <link rel="stylesheet" type="text/css" href="{% static 'css/nav_orange.css' %}" />
  <title>기본정보 상세</title>
  <style>
    .nav_box a:nth-child(3) {
      color: #003a38;
    }
  </style>
</head>

<body>

  {% include 'shared/_navbar.html' %}
  <div class="_1">
    <div><i class="fas fa-cog"></i> 기본정보 설정</div>
    <div id="btn">
      <a href="{% url 'users:edit_profile' %}">정보 수정하기</a>
    </div>
  </div>

  <img src="{{profile.profile_pic.url}}" />

  <div class="_4">
    <div class="fix">닉네임</div>
    <div class="user">{{profile.nickname}}</div>
  </div>

  <div class="_5">
    <div class="title">기본정보</div>

    <div class="carrotbox">
      <div class="whitebox">
        <div class="fix">이름</div>
        <div class="user">{{profile.name}}</div>
      </div>
      <div class="whitebox">
        <div class="fix">이메일</div>
        <div class="user">{{profile.user.email}}</div>
      </div>
      <div class="notice" style="color: gray;">
        <a href="{% url 'accounts:pw_finder' %}"
        style="text-decoration: underline"
        >비밀번호 변경 바로가기</a
      ></div>
    </div>
  </div>

  <div class="_6">
    <div class="title">문의하기</div>
    <div class="graybox">
      <a href="https://open.kakao.com/o/sYPcn6rf">카카오톡 1:1 채팅방 링크 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <i class="fas fa-link"></i></a>
    </div>
    <div class="graybox"> <a style="color:#aaaaaa;">이메일</a> &nbsp;likelion_coggiri@gmail.com</div>
  </div>

  <div class="_7">
    <a href="{% url 'accounts:delete_account' %}" onclick="return confirm('확인 버튼 클릭 시 탈퇴되며, 복구할 수 없습니다. 진행하시겠습니까?');">이거누르면바로탈퇴임</a>
  </div>
</body>

</html>

users/templates/users/detail_rcv_apply.html
<!DOCTYPE html>
<html lang=" ko">
{% load static %}

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/detail_rcv_apply.css' %}" />
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Co/mpatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav_orange.css' %}" />
  <title>16-1지원관리(관리자)</title>
</head>

<body>
  {% include 'shared/_navbar.html' %}
  <div class="_1">
    APPLY
    <div>
      <i class="fas fa-cog" style="font-size: 32px"></i>
      <a href="{% url 'users:detail_profile' %}">내 정보 수정</a>
    </div>
  </div>

  <section class="white">
    <div class="_3">
      지원자 포트폴리오
    </div>

    <div class="_2">
      {% if apply.status == 'under_review' %}


      <div class="btn"><a onclick="prom('accept')">지원수락</a></div>
      <div class="btn"><a onclick="prom('reject')">지원 거절</a></div>

      {% else %} 이미 검토가 끝난 지원서입니다 {% endif %}
    </div>

    <div class="_4">
      <div class="fix">지원 한마디</div>
      <div class="ment">{{apply.short_text}}</div>
    </div>

    <div class="_4">
      <div class="fix">닉네임</div>
      <div class="whitebox">{{profile.nickname}}</div>
    </div>

    <div class="_4">
      <div class="fix">나이</div>
      <div class="whitebox"> {{profile.age}}</div>
    </div>

    <div class="_4">
      <div class="fix">성별</div>
      <div class="whitebox">{{profile.gender}}</div>
    </div>

    <div class="_4">
      <div class="fix">학력</div>
      <div class="whitebox">{{profile.major}}</div>
    </div>

    <div class="_4">
      <div class="fix">연락 SNS 주소</div>
      <div class="whitebox">{{profile.contact}}</div>
    </div>

    <div class="_4">
      <div class="fix">자기소개</div>
      <div class="intro">{{profile.about_me}}</div>
    </div>

    </div>
  </section>

  <div id="color">
    <a href="{% url 'users:apply_manager' 'rcv_apply' %}">지원 관리로 돌아가기</a>
  </div>
</body>
<script>
  function sendDataToDjango(status, userInput) {
    fetch("{% url 'users:respond_apply' %}", {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRFToken': '{{ csrf_token }}'
      },

      body: JSON.stringify({ status: status, id: '{{apply.pk}}', reply: userInput })
    })
      .then(response => {
        if (response.ok) {
          location.reload()
          // 성공적으로 응답을 받은 경우 처리
          console.log("Data sent successfully!");
        } else {
          // 응답이 실패한 경우 처리
          location.reload()
          console.error("Failed to send data to Django.");
        }
      })
      .catch(error => {
        location.reload()
        // 네트워크 오류 등 예외 처리
        console.error("Error while sending data to Django:", error);
      });
  }


  function prom(status) {
    var userInput = '';
    if (status === 'accept') {
      userInput = window.prompt("짧은 연락처를 남겨주세요!", "")
    }
    sendDataToDjango(status, userInput);
  }
</script>

<script>

function openChild() {
  window.name = "parentForm";
  



}

</script>

</html>

users/templates/users/edit_portfolio.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/edit_portfolio.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Co/mpatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet" />

    <title>나의 포트폴리오</title>

</head>

<body>

    <div id="button">
        MY PROTFOLIO
        <div>
          <i class="fas fa-cog" style="font-size: 32px"></i>
          <a href="{% url 'users:detail_profile' %}">내 정보 수정</a>
        </div>
      </div>

    <form action="{% url 'users:mypage' %}" method="POST">
        {% csrf_token %}

        <div class="white">
          <div class="box3">
            <p>필수 작성 항목</p>
            <div id="notice" style="color: #747474;">아래의 항목은 꼭 기입해주세요<br>
            <p>닉네임, 나이, 성별, 학적사항, 연락 SNS 주소</p></div>
          </div>

          <div class="box">
            <p>닉네임</p>
            <div id="block">{{profile.nickname}}</div>
          </div>

          <div class="box2">
            <div id="minibox">
              <p>나이</p>
              <div id="block2"> <input type="number" value="{{profile.age}}" name="age" placeholder="나이 입력"></div>
            </div>
      
            <div id="minibox">
              <p>성별</p>
              <div id="block2"><select name="gender" class="pl">
                {% for choice in profile.gender_choices %}
                <option value="{{ choice.0 }}" {% if profile.gender == choice.0 %}selected{% endif %}>
                    {{ choice.1 }}
                </option>
                {% endfor %}
            </select>
          </div>
            </div>
          </div>

          <div class="box">
            <p>학과</p>
            <div id="block"><input type="text" value="{{profile.major}}" name="major" placeholder="학과 입력"></div>
          </div>

          <div class="box">
            <p>연락 SNS 주소</p>
            <div id="block">
              <textarea name="contact" placeholder="이메일, 카카오톡 아이디, 오픈채팅방 링크 등 SNS주소 입력">{{profile.contact}}</textarea>
            </div>
          </div>

          <div class="box">
            <p>자기소개</p>
            <div id="block">
              <textarea name="about_me" placeholder="자유롭게 본인을 소개해주세요 &#10;스펙/자격증/각오 등을 기입해주세요">{{profile.about_me}}</textarea>
            </div>

      </div>
        <div class="submit">
        <input type="submit" value="수정완료"></div>
    </form>
    
    <!-- <p>{{profile.nickname}}</p>
    <div>
        <p>이름 : {{profile.name}}</p>
        <p>이메일 : {{profile.user.email}}</p>
        <a href="{% url 'accounts:pw_finder' %}">비밀번호 수정 버튼</a>
    </div>
    <a href="{% url 'accounts:delete_account' %}">회원 탈퇴하기</a> -->

</body>

</html>

users/templates/users/edit_profile.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
  <meta charset="UTF-8" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/detail_portfolio.css' %}" />
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Co/mpatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav_orange.css' %}" />
  <style>
    .nav_box a:nth-child(3) {
      color: #003a38;
    }
  </style>
  <title>기본정보</title>
</head>

<!-- 13-3. 기본정보_수정 페이지 -->

<body>
  {% include 'shared/_navbar.html' %}
  <form action="{% url 'users:update_profile_pic' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="_1">
      <div><i class="fas fa-cog"></i> 기본정보 설정</div>
      <input type="submit" name="action" value="수정완료" />
    </div>

    <div class="_2">
      <img src="{{profile.profile_pic.url}}" alt="프로필이미지" />
    </div>

    <div class="_3">
      <label for="file">
        <div class="button"><i class="fas fa-camera"></i> &nbsp; 사진 올리기</div>
      </label>
      <input type="file" name="file" id="file" style="display: none;">
      
      <div class="button">
        <input type="submit" name="action" value="기본 이미지로 변경" />
      </div>
    </div>
  </form>

  <div class="_4">
    <div class="fix">닉네임</div>
    <div class="user">
      <p>{{profile.nickname}}</p>
    </div>
  </div>

  <div class="_5">
    <div class="title">기본정보</div>

    <div class="carrotbox">
      <div class="whitebox">
        <div class="fix">이름</div>
        <div class="user">
          <p>{{profile.name}}</p>
        </div>
      </div>
      <div class="whitebox">
        <div class="fix">이메일</div>
        <div class="user">{{profile.user.email}}</div>
      </div>
      <div class="whitebox">
        <a href="{% url 'accounts:pw_finder' %}" style="text-decoration: underline">비밀번호 변경 바로가기</a>
      </div>
    </div>
  </div>
</body>

</html>

users/templates/users/mypage.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav_orange.css' %}" />

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet" />
  <style>
    .nav_box a:nth-child(3) {
      color: #003a38;
    }
  </style>

  <title>마이페이지</title>
</head>


<body>
  {% include 'shared/_navbar.html' %}

  <div id="button">
    나의 페이지
    <div>
      <a href="{% url 'users:detail_profile' %}"><i class="fas fa-cog" style="font-size: 32px"></i>내 정보 수정</a>
    </div>
  </div>

  <div id="beige">
    <img src="{{ profile.profile_pic.url }}" alt="프로필 이미지" />
    <p>{{profile.nickname}}</p>
  </div>

  <div class="center">
    <div id="admin">
      <a href="{% url 'users:apply_manager' 'rcv_apply' %}">지원 관리</a>
    </div>
  </div>

  <div class="portfolio">
    <div id="title">
      MY PORTFOLIO
      <div id="fix"><a href="{% url 'users:edit_portfolio' %}">수정</a></div>
    </div>

    <div id="box">
      <p>닉네임</p>
      <div id="block">{{profile.nickname}}</div>
    </div>

    <div id="box2">
      <div id="minibox">
        <p>나이</p>
        <div id="block2">{{profile.age}}</div>
      </div>

      <div id="minibox">
        <p>성별</p>
        <div id="block2">{{profile.gender}}</div>
      </div>
    </div>

    <div id="box">
      <p>학력</p>
      <div id="block">{{profile.major}}</div>

      <p>연락 SNS 주소</p>
      <div id="block">{{profile.contact}}</div>

      <p>자기소개</p>
      <div id="block">{{profile.about_me}}</div>
    </div>
  </div>

  <div id="logout">
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
  </div>
</body>

</html>