Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/',signup,name="signup"),
    path('send_email/',send_email,name="send_email"),
    path('verify_email/',verify_email,name="verify_email"),
    path('pw_finder/',pw_finder,name="pw_finder"),
    path('delete_account/', delete_account,name="delete_account"),
    path('terms_of_use/',terms_of_use,name="terms_of_use"),
    path('privacy/',privacy,name="privacy"),
    path('nickname_redundant_check/',nickname_redundant_check,name="nickname_redundant_check"),
]

main/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name ="main"
urlpatterns = [
    path('', start, name="start"),
    path('mainpage_competition', mainpage_competition, name="mainpage_competition"),
    path('mainpage_entrepreneur/', mainpage_entrepreneur, name="mainpage_entrepreneur"),
    path('mainpage_supporters/', mainpage_supporters, name="mainpage_supporters"),
    path('search/<str:f>', search, name="search"),
    path('second.html', second, name="second"),
    path('guide/', guide, name="guide"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'
urlpatterns = [
    path('write/', write, name="write"),
    path('new/', new, name="new"),
    path('crew_search/<int:id>', detail, name="detail"),
    path('temporary_save_post', temporary_save_post, name="temporary_save_post"),
    path('wrote_post', wrote_post, name="wrote_post"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/', mypage, name="mypage"),
    path('detail_profile/', detail_profile, name="detail_profile"),
    path('update_profile_pic/',update_profile_pic, name="update_profile_pic"),
    path('edit_portfolio/',edit_portfolio, name="edit_portfolio"),
    path('edit_profile/',edit_profile, name="edit_profile"),
    path('apply_manager/<str:page>',apply_manager, name="apply_manager"),
    path('detail_apply/<str:page>/<int:id>',detail_apply, name="detail_apply"),
    path('respond_apply',respond_apply, name="respond_apply"),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from post.models import Post, TrackKey, FieldKey
from django.db.models import Q


# Create your views here.
def start(request):
    return render(request, 'main/start.html')

def second(request):
    return render(request, 'main/second.html')
def guide(request):
    return render(request, 'main/guide.html')

def mainpage_competition(request):
    competition = FieldKey.objects.get(fieldKey = "공모전")
    project = FieldKey.objects.get(fieldKey = "프로젝트")
    posts_com = competition.post.filter(isSave=True)
    posts_pro = project.post.filter(isSave=True)
    
    posts = posts_com.union(posts_pro)[:4]

    return render(request, 'main/mainpage_competition.html', {'posts':posts})

def mainpage_supporters(request):
    supporters = FieldKey.objects.get(fieldKey = "대외활동")
    posts = supporters.post.filter(isSave=True)[:4]
    return render(request, 'main/mainpage_supporters.html', {'posts':posts})

def mainpage_entrepreneur(request):
    entrepreneur = FieldKey.objects.get(fieldKey = "창업")
    posts = entrepreneur.post.filter(isSave=True)[:4]
    return render(request, 'main/mainpage_entrepreneur.html', {'posts':posts})

def search(request, f):
    if request.method == 'POST':
        typed_word = request.POST.get('word')  # 검색어
        selected_field = request.POST.get('field') # 모집 분야
        selected_track = request.POST.get('track') # 모집 트랙

        # word로 가져온 post 
        if typed_word == "":
            word_posts = Post.objects.filter(isSave = True)
            print(word_posts)
        else:
            word_posts = Post.objects.filter(title__contains = typed_word, isSave = True)

        # field로 가져온 post
        if selected_field != "전체":
            searched_field = FieldKey.objects.get(fieldKey = selected_field)
        # track으로 가져온 post
        if selected_track != "전체":
            searched_track = TrackKey.objects.get(trackKey = selected_track)

        if selected_field == "전체" and selected_track != "전체":
            posts = word_posts.filter(trackKey = searched_track)
        elif selected_track == "전체" and selected_field !="전체":
            posts = word_posts.filter(fieldKey = searched_field)
        elif selected_field !="전체" and selected_track != "전체":
            posts = word_posts.filter(Q(fieldKey = searched_field) & Q(trackKey = searched_track))
        elif selected_field == "전체" and selected_track == "전체":
            posts = word_posts

        return render(request, 'main/search.html', {'posts': posts})
    
    if request.method == 'GET':
        if f=='project':
            competition = FieldKey.objects.get(fieldKey = "공모전")
            project = FieldKey.objects.get(fieldKey = "프로젝트")
            posts_com = competition.post.filter(isSave=True)
            posts_pro = project.post.filter(isSave=True)
            posts = posts_com.union(posts_pro)
            return render(request, 'main/search.html', {'posts':posts})
        elif f=='supporters':
            supporters = FieldKey.objects.get(fieldKey = "대외활동")
            posts = supporters.post.filter(isSave=True)
            return render(request, 'main/search.html', {'posts':posts})
        elif f=='entre':
            entrepreneur = FieldKey.objects.get(fieldKey = "창업")
            posts = entrepreneur.post.filter(isSave=True)
            return render(request, 'main/search.html', {'posts':posts})

main/templates/main/guide.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static '/css/guide.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />

    <title>이용 가이드</title>
</head>

<body>
    <section class="container">
        <div class="logo_bar">
            <div id="logo_img"></div>
            <div id="logo_letter"></div>
        </div>
        <div id="logo">
            <a href="javascript:window.history.back();"><i class="fas fa-home" style="font-size: 40px;"></i><p>&nbsp; 홈으로 돌아가기</p></a>
        </div>
        <div class="img">
        </div>
    </section>
</body>
</html>

main/templates/main/mainpage_competition.html
{% extends 'base_mainpage.html' %}
{% block style %}
<style>
    .showteambar {
        width: 390px;
        background-color: rgba(102, 192, 129, 0.7);
        display: flex;
        flex-direction: column;
        padding: 20px 20px;
    }
</style>
{% endblock %}

{% block teamlist %}

<section class="showteambar">
    <p>지금 모집중인 팀</p>
    {% if posts %}
        {% for post in posts %}
        <a href="{% url 'post:detail' post.id %}">   
            <div class="team">
                <div id="team_pic">
                    <img src="{{ post.image.url }}" alt="사진">
                </div>
                <div id="team_exp">
                    <p>{{ post.team_name }}</p>
                    <p>{{ post.title }}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    {% else %}
        <p>현재 모집하고 있는 팀이 없습니다.</p>
    {% endif %}
    <a href="{% url 'main:search' 'project' %}">
        <h1>더보기 ▶</h1>
    </a>
    </section>
    

{% endblock %}

main/templates/main/mainpage_entrepreneur.html
{% extends 'base_mainpage.html' %}
{% block style %}
<style>
    .showteambar {
        width: 390px;
        background-color: #1A4E4C;
        display: flex;
        flex-direction: column;
        color: white;
        padding: 20px 20px;
    }
</style>
{% endblock %}

{% block teamlist %}
<section class="showteambar">
    <p>지금 모집중인 팀</p>
    {% if posts %}
        {% for post in posts %}
        <a href="{% url 'post:detail' post.id %}">
            <div class="team">
                <div id="team_pic">
                    <img src="{{ post.image.url }}" alt="사진">
                </div>
                <div id="team_exp">
                    <p>{{ post.team_name }}</p>
                    <p>{{ post.title }}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    {% else %}
        <p>현재 모집하고 있는 팀이 없습니다.</p>
    {% endif %}

    <a href="{% url 'main:search' 'entre' %}">
        <h1 style="color:white">더보기 ▶</h1>
    </a>
</section>
{% endblock%}

main/templates/main/mainpage_supporters.html
{% extends 'base_mainpage.html' %}
{% block style %}
<style>
    .showteambar {
        width: 390px;
        background-color: rgba(255, 136, 89, 0.7);
        display: flex;
        flex-direction: column;
        padding: 20px 20px;
    }
</style>
{% endblock %}

{% block teamlist %}

<section class="showteambar">
    <p>지금 모집중인 팀</p>
    {% if posts %}
        {% for post in posts %}
        <a href="{% url 'post:detail' post.id %}">
            <div class="team">
                <div id="team_pic">
                    <img src="{{ post.image.url }}" alt="사진">
                </div>
                <div id="team_exp">
                    <p>{{ post.team_name }}</p>
                    <p>{{ post.title }}</p>
                </div>
            </div>
        </a>
        {% endfor %}
        {% else %}
        <p>현재 모집하고 있는 팀이 없습니다.</p>
        {% endif %}
    
    <a href="{% url 'main:search' 'supporters' %}">
        <h1>더보기 ▶</h1>
    </a>
    </section>
</section>
{% endblock%}

main/templates/main/search.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/search.css' %}?after" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
    <title>post</title>
</head>

<body>
    <section class="container">
        <section class="header">
            <div class="nav_top">
                <div class="nav_box" style="border: solid 3px;">
                    {% if user.is_authenticated %}
                    <a href="{% url 'post:wrote_post' %}"><i class="fas fa-pen" class="nav_i" id="nav_pen"></i></a>
                    <a href="{% url 'main:mainpage_competition' %}"><i class="fas fa-home" class="nav_i"
                            id="nav_home"></i></a>
                    <a href="{% url 'users:mypage' %}"><i class="fas fa-user" class="nav_i" id="nav_user"></i></a>
                    {% else %}
                    <a href="{% url 'accounts:login' %}" onclick="return confirm('로그인 후 이용해주세요');"><i class="fas fa-pen"
                            class="nav_i" id="nav_pen"></i></a>
                    <a href="{% url 'main:mainpage_competition' %}"><i class="fas fa-home" class="nav_i"
                            id="nav_home"></i></a>
                    <a href="{% url 'accounts:login' %}" onclick="return confirm('로그인 후 이용해주세요');"><i
                            class="fas fa-user" class="nav_i" id="nav_user"></i></a>
                    {% endif %}
                </div>
            </div>

            <section class="searchbar">
                <form action="{% url 'main:search' ' ' %}" method="POST">
                    {% csrf_token %}
                    <div class="search_row1">
                        <input type="text" name="word" id="" placeholder="Search">
                        <button type="submit" name="submit" id="submit_btn">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>

                    <div class="search_row2">
                        <div>
                            <select name="field" id="search_field">
                                <option value="전체">모집 분야</option>
                                <option value="공모전">공모전</option>
                                <option value="프로젝트">프로젝트</option>
                                <option value="대외활동">대외활동</option>
                                <option value="창업">창업</option>
                            </select>
                        </div>
                        <div>
                            <select name="track" id="search_track">
                                <option value="전체">모집 트랙</option>
                                <option value="기획">기획</option>
                                <option value="마케터">마케터</option>
                                <option value="영상">영상</option>
                                <option value="디자인">디자인</option>
                                <option value="개발">개발</option>
                                <option value="기자단">기자단</option>
                                <option value="봉사">봉사</option>
                                <option value="기타">기타</option>
                            </select>
                        </div>
                    </div>
                </form>
            </section>

            <section class="search_text">
                <h1>검색 결과</h1>
            </section>

            <section class="show_result">
                {% if posts %}
                {% for post in posts %}

                <div class="result_item">
                    <div class="picture">
                        <a href="{% url 'post:detail' post.id %}">
                            <div id="result_pic">
                                {% if post.fieldKey.first.fieldKey == "공모전" %}
                                <div id="result_cate" style="background-color: #66C081;">
                                    <p>공모전</p>
                                </div>
                                {% elif post.fieldKey.first.fieldKey == "프로젝트" %}
                                <div id="result_cate" style="background-color: #66C081;">
                                    <p>프로젝트</p>
                                </div>
                                {% elif post.fieldKey.first.fieldKey == "대외활동" %}
                                <div id="result_cate" style="background-color: #FF8859">
                                    <p>대외활동</p>
                                </div>
                                {% elif post.fieldKey.first.fieldKey == "대외활동" %}
                                <div id="result_cate">
                                    <p>대외활동</p>
                                </div>
                                {% else %}
                                <div id="result_cate">
                                    <p>창업</p>
                                </div>
                                {% endif %}
                                <img src="{{ post.image.url }}" alt="사진">
                            </div>
                        </a>
                    </div>
                    
                    <div class="explain">
                        <div id="result_exp">
                            <p><a href="{% url 'post:detail' post.id %}" style="color:#66C081">{{ post.team_name }} </a> <a href="{% url 'post:detail' post.id %}">{{ post.title }} </a></p>
                        </div>
                    </div>

                </div>

                {% endfor %}
                {% else %}
                {% endif %}
            </section>




        </section>
    </section>


</body>

main/templates/main/second.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>second</title>
    <meta http-equiv="refresh" content="1.5; url={% url 'main:mainpage_competition' %}">

</head>
<body style="margin:0px;">
    <div style="background-image:url('{% static 'images/loading.jpg' %}'); background-size: 100% 100%; height:800px; width:430px;" class="container"></div>
</body>
</html>

main/templates/main/start.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/start.css' %}">
<head>
    <input id="modalToggle" class="hide" type="checkbox">
<section class="modal">
    <label class="btn btn-open" for="modalToggle"></label>
    
    <div class="inside">
        <label class="btn-close" for="modalToggle"></label>
    </div>
    
    </section>
    <meta http-equiv="refresh" content="1.7; url={% url 'main:second' %}">
</body>

</html>